# Generated by Django 5.2.6 on 2025-09-09 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.source', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(unique=True, verbose_name='Текст цитаты'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Вес для случайного выбора'),
        ),
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название источника'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('film', 'Фильм'), ('book', 'Книга')], default='film', max_length=10, verbose_name='Тип источника'),
        ),
    ]
