# Generated by Django 5.2.6 on 2025-09-09 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_created_at_alter_quote_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-likes', '-views', '-created_at'], 'verbose_name': 'Цитата', 'verbose_name_plural': 'Цитаты'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Источник', 'verbose_name_plural': 'Источники'},
        ),
        migrations.RemoveField(
            model_name='source',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='source',
            name='title',
        ),
        migrations.AddField(
            model_name='source',
            name='name',
            field=models.CharField(default=12, max_length=255, unique=True, verbose_name='Название источника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.source', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Вес (чем выше — тем чаще выдаётся)'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('film', 'Фильм'), ('book', 'Книга'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип'),
        ),
    ]
